### ISSUE TITLE
AH01328: Line too long, URI /css2  

### ISSUE THREAD

**Issue by remileblond67076** [trajano/google-fonts-proxy-docker#4]
I use this code for https://fonts.strasbourg.eu.

When I call this URL : https://fonts.strasbourg.eu/css2?family=Open+Sans:wght@700&display=swap

I get this error message on console :

` [substitute:error] [pid 10:tid 139743874636600] [client 10.233.67.114:46764] AH01328: Line too long, URI /css2 `

**Comment by remileblond67076** [comment]
And the response is truncated

**Comment by trajano** [comment]
Looks ok when I tried 

```
curl -v 'https://fonts.strasbourg.eu/css2?family=Open+Sans:wght@700&display=swap'
```

**Comment by remileblond67076** [comment]
Is this URL OK for you ? : [https://fonts.strasbourg.eu/css2?family=Open+Sans&display=swap](https://fonts.strasbourg.eu/css2?family=Open+Sans&display=swap)

In my case, the response is truncated :

![image](https://github.com/trajano/google-fonts-proxy-docker/assets/65656372/8eda30c2-e32f-4e02-b364-883e8a614f97)

And I get this message on my server :

```
│ [Wed Jan 10 15:17:42.642959 2024] [substitute:error] [pid 92:tid 139743875341112] [client 10.233.65.134:33550] AH01328: Line too long, URI /css2 
```

**Comment by remileblond67076** [comment]
This PR fix this bug : https://github.com/trajano/google-fonts-proxy-docker/pull/5
